// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0q3x7OzZ4HlEofjck8tZO_DtSNV2gYRg',
    appId: '1:951619711563:web:b558d814024097696e53ce',
    messagingSenderId: '951619711563',
    projectId: 'tambakudangv2',
    authDomain: 'tambakudangv2.firebaseapp.com',
    storageBucket: 'tambakudangv2.appspot.com',
    measurementId: 'G-DT28HFYRZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCETFR0pcF8Lmy4xjecVTr3cWvbOwelMSY',
    appId: '1:951619711563:android:e716ad71f2ceed8b6e53ce',
    messagingSenderId: '951619711563',
    projectId: 'tambakudangv2',
    storageBucket: 'tambakudangv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0d3eIMPE7q44Ev4fNoP05uq2jo8LtNhw',
    appId: '1:951619711563:ios:49084488c9e445056e53ce',
    messagingSenderId: '951619711563',
    projectId: 'tambakudangv2',
    storageBucket: 'tambakudangv2.appspot.com',
    iosClientId: '951619711563-rsvro3tu39015updm56ppjq6p62b5t7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.tambakUdangV2',
  );
}
